BulletTech/BulletTech

docs/Dessert_blog/Apps/2021-06-06-Notion.md

[Dessert] - Notion post 

---

docs/Dessert/Apps/2021-06-15-Hotapps.md

[Dessert] - Hotapps post

---

docs/Main_Course/Data_Analytics/2021-07-01-pdf-Crawler.md

[Main Course] - pdf crawler

---

docs/Main_Course/Data_Analytics/2021-07-24-notes-of-rules-of-ML2.0.md

Post for notes of rules of ML2.0

[Main Course] - Notes of rules of ML2.0

---

docs/Main_Course/Data_Analytics/2021-08-03-useful-python-packages.md

Post for useful python packages

[Main Course] - Useful python packages

---

material/assets_v2/css/style.css
material/overrides/home.html

Fixes # (Fix the CSS conflicts on Home)

[Foundation] - Fix the CSS conflicts on Home

---

docs/Main_Course/Coding/2021-09-21-Python-Closure.md

[Main Course] - Python Closure

---

docs/Main_Course/Deep_Learning/2021-10-04-Keras-Custom-Model.md

Fixes # (tf.keras custom model)

[Main Course] - tf.keras custom model

---

docs/Main_Course/Deep_Learning/2021-10-02-TF-Callbacks.md
docs/Main_Course/Deep_Learning/2021-10-10-TF-on-M1-Mac.md

Fixes # (Tensorflow on Apple Silicon Macs)

[Main Course] - Tensorflow on Apple Silicon Macs

---

docs/Main_Course/Analytics_Tools/2021-10-14-play-with-github.md
docs/Main_Course/Analytics_Tools/2021-11-01-GitHub-Resume.md
mkdocs.yml

[Main Course] - GitHub resume

---

docs/Main_Course/One_Day_Build/2021-10-29-flaskbb2.md

[Main Course] - Flaskbb2.0

---

docs/Main_Course/Deep_Learning/2021-11-04-Deep-Learning-101-ResNet.md

[Main Course] - ResNet demo

---

docs/Main_Course/Analytics_Tools/2021-11-13-GitHub-Action.md
mkdocs.yml

[Main Course] - GitHub Action Intro

---

docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md

[Main Course] - Docker Windows

---

docs/Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
docs/Main_Course/Analytics_Tools/2021-11-20-GitHub-Docker.md
mkdocs.yml

[Main Course] - Gh action docker

---

docs/Main_Course/Coding/2021-11-21-Python-argparse.md

[Main Course] - Argparse

---

docs/Main_Course/Analytics_Tools/2021-11-25-Docker-Volumes.md
mkdocs.yml

[Main Course] - Docker Volumes

---

docs/Main_Course/One_Day_Build/2021-11-27-fund_data.md

Post for fund data(not for posting)

[Main Course] - fund data

---

docs/Main_Course/Deep_Learning/2021-12-01-Tensorflow-Doc.md

[Main Course] - Tensorflow Handbook

---

docs/Main_Course/Deep_Learning/2021-12-18-Tabnet.md

[Main Course] - Tabnet

---

docs/Dessert/Apps/2021-12-25-Apache.md

[Main Course] - Apache

---

docs/Main_Course/Deep_Learning/12-27-TensorFlow-Recommender2.md
docs/Main_Course/Deep_Learning/2021-12-27-TensorFlow-Recommender2.md
mkdocs.yml

[Main Course] - TensorFlow Recommender 2

---

docs/Main_Course/Machine_Learning/2022-01-28-Ensemble-Learning.md
mkdocs.yml

[Main Course] - Ensemble Learning

---

docs/Main_Course/Data_Analytics/2022-01-30-Kaggle-exp-s2.md

[Main Course] - Kaggle量化竞赛Top 1方案

---

docs/Main_Course/Graph_Database/2022-04-09-Neo4J-Fraud-S4.md

[Main Course] - Neo4J-Fraud-S4 

---

docs/Main_Course/Deep_Learning/2022-04-16-TF-Text-Classification.md

[Main Course] - 使用TensorFlow进行文本分类

---

docs/Main_Course/Deep_Learning/2022-05-07-TF-Playground.md
mkdocs.yml

[Main Course] - TF playground

---

docs/Main_Course/Deep_Learning/2022-05-20-CNN-Explainer.md

[Main Course] - CNN Explainer

---

docs/Main_Course/Deep_Learning/2022-05-23-TF-Img-Classification.md
mkdocs.yml

[Main Course] - 使用TensorFlow进行图片分类

---

docs/Dessert/Apps/2022-05-28-SageMaker-Studio-Lab.md
mkdocs.yml

Fixes # (免费实验平台 - Amazon SageMaker Studio Lab)

[Dessert] - 免费实验平台 - Amazon SageMaker Studio Lab
